version: "3.8"
name: kohya-ss

services:
  kohya:
    image: ghcr.io/neggles/kohya-ss-docker:latest
    restart: unless-stopped
    container_name: kohya-ss
    build:
      context: ./docker
      dockerfile: Dockerfile
      target: kohya
    environment:
      CLI_ARGS: "--listen 0.0.0.0"
      KOHYA_PORT: 7681
      # make TQDM behave a little better
      PYTHONUNBUFFERED: "1"
      TERM: "${TERM}"
      NVIDIA_DRIVER_CAPABILITIES: compute,utility,graphics
      NVIDIA_VISIBLE_DEVICES: 0
    ports:
      - mode: ingress
        target: 7681
        published: 7681
        protocol: tcp
      - mode: ingress
        target: 6006
        published: 6006
        protocol: tcp
    volumes:
      - type: bind
        source: ./data
        target: /data
      - type: bind
        source: ./kohya
        target: /data/kohya
      - type: bind
        source: /usr/local/cuda-12.0
        target: /usr/local/cuda
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              device_ids: [ "0" ]
