services:
  webui:
    image: sd-webui:50
    restart: unless-stopped
    container_name: sd-webui
    build:
      context: ./docker
      dockerfile: Dockerfile
      target: app
    environment:
      CLI_ARGS: --allow-code --xformers --enable-insecure-extension-access --api
      PYTHONUNBUFFERED: "1"
      TERM: "${TERM}"
    ports:
      - mode: ingress
        target: 7860
        published: 7860
        protocol: tcp
    volumes:
      - type: bind
        source: ./data
        target: /data
      - type: bind
        source: ./output
        target: /output
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              device_ids: [ "0" ]
