name: Docker Build
run-name: Docker Build (${{ github.event_name }})

on:
  push:
    branches:
      - "main"
      - "release"
    paths:
      - "docker/*"
      - "Dockerfile*"
      - "start.py"
      - ".github/workflows/build-push.yml"
      - "!**.md"
  workflow_dispatch:
    inputs:
      force-push:
        description: "push to GHCR"
        type: boolean
        required: true
        default: false

  pull_request:
    paths:
      - docker/

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_PLATFORMS: "linux/amd64"

jobs:
  build:
    name: Build CUDA
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: ${{ env.IMAGE_PLATFORMS }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.IMAGE_REGISTRY }}/${{ github.repository }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,prefix=rev-,format=short
            type=edge
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr

      - name: Build and Push Versioned Tags
        uses: docker/build-push-action@v3
        with:
          context: ./docker
          file: ./docker/Dockerfile
          platforms: ${{ env.IMAGE_PLATFORMS }}
          push: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || inputs.force-push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=build-${{ github.repository }}
          cache-to: type=gha,mode=max,scope=build-${{ github.repository }}
