name: kohya_ss Docker Build
run-name: Kohya Build (${{ github.event_name }})

on:
  push:
    branches:
      - "main"
      - "release"
    paths:
      - "docker/*"
      - "!docker/entrypoint_webui.sh"
      - ".github/workflows/build-push-kohya.yml"
      - "!**.md"

  workflow_dispatch:
    inputs:
      force-push:
        description: "push to GHCR"
        type: boolean
        required: true
        default: false

  pull_request:
    paths:
      - "docker/"
      - "docker-bake.hcl"
      - "docker-compose.kohya.yml"
      - ".github/workflows/build-push-kohya.yml"

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

env:
  KOHYA_SS_REF: 63657088f4c35a376dd8a936f53e9b9a3b4b1168
  IMAGE_REGISTRY: ghcr.io
  IMAGE_NAME: neggles/kohya-ss-docker
  IMAGE_PLATFORMS: "linux/amd64"

jobs:
  build:
    name: Build (CUDA)
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: ${{ env.IMAGE_PLATFORMS }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,prefix=rev-,format=short
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr

      - name: Upload metadata bake file as artifact
        id: meta-artifact
        uses: actions/upload-artifact@v3
        with:
          name: meta
          path: ${{ steps.meta.outputs.bake-file }}

      - name: Build and Push Versioned Tags
        id: build-push
        uses: docker/bake-action@v3
        with:
          targets: kohya
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          push: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || inputs.force-push }}
