name: WebUI Docker Build
run-name: WebUI Build (${{ github.event_name }})

on:
  push:
    branches:
      - "main"
      - "release"
    paths:
      - "docker/*"
      - "!docker/entrypoint_kohya.sh"
      - ".github/workflows/build-push.yml"
      - "!**.md"

  workflow_dispatch:
    inputs:
      force-push:
        description: "push to GHCR"
        type: boolean
        required: true
        default: false

  pull_request:
    paths:
      - "docker/"
      - "docker-bake.hcl"
      - "docker-compose.yml"
      - ".github/workflows/build-push.yml"

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

env:
  AUTO_STABLE_REF: a9fed7c364061ae6efb37f797b6b522cb3cf7aa2
  IMAGE_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_PLATFORMS: "linux/amd64"

jobs:
  build:
    name: Build (CUDA)
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        include:
          - name: "AUTOMATIC1111 (Latest)"
            target: "auto-latest"
            tags: |
              type=raw,value=latest,enable={{is_default_branch}}
              type=raw,value=latest-{{date 'YYYYMMDD'}},enable={{is_default_branch}}
              type=sha,prefix=latest-,format=short
              type=ref,event=branch
              type=ref,event=tag
              type=ref,event=pr

          - name: "AUTOMATIC1111 (Stable)"
            target: "auto-stable"
            tags: |
              type=raw,value=stable,enable={{is_default_branch}}
              type=raw,value=stable-{{date 'YYYYMMDD'}},enable={{is_default_branch}}
              type=sha,prefix=stable-,format=short
              type=semver,pattern={{version}}
              type=semver,pattern={{major}}.{{minor}}

          - name: "vladmandic (latest)"
            target: "vlad"
            tags: |
              type=raw,value=vlad,enable={{is_default_branch}}
              type=sha,prefix=vlad-,format=short

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: ${{ env.IMAGE_PLATFORMS }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: ${{ matrix.tags }}

      - name: Build and Push Versioned Tags
        id: build-push
        uses: docker/bake-action@v3
        with:
          targets: ${{ matrix.target }}
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          push: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || inputs.force-push }}
          cache-from: type=gha,scope=build-${{ github.repository }}
          cache-to: type=gha,mode=max,scope=build-${{ github.repository }}
